language: php
script: ''
deploy:
  provider: codedeploy
  access_key_id: AKIAIY5E5ZM7OHBWAQZA
  secret_access_key:
    secure: WfPZ2gV3aXtHOfjtDp1bV2LAiLoMJnXRMbd5nq5/DwJKnbc6sHOTllxL/gI9US2zRanaHtCynr7mbsvGo2OsR89YEhnY5ikXRdzA9boYDxcdwmdqiNxQqXpSZqxas/c0e19EwxwPEG0AuCMvrXjLbBI1ZntzygcQ9eEOls2HM2GuSXlC/53Fluv4N9yitavWQIVB8fObvGPa9gETXyh7wYn9EVtfgF3LJ5bBF+DZk6dssXRguSelWQttmJId0hO1xvmCc0R5gs/K7QAxWwtgCly1s4JLd4ZMenrn+sVtNR2qGvdgGk0yD2DOvNNjPLI4OgyvEe1dV76vGJ1gUAjodJG+0POjHb0RVH0E5EpwjhF44j/EgC+SdWUuNgYCUPty84g5I2UoPnPlngr7MFVvS6JQkNl/+GG6XPIWSElyiuuwMHZqnD9c4pLCtoTNnI80mUSS6YI+EWTrVyT/WRwwbfyyO5UVRvx6tTZZpsK6PO3xwtgRE0djxEvExxjD6r1p9bgf3K8UNloKmHRWcoa1uNP9e/y+b+zi0lIurqtn7Cm5CJqNx2WN7swIGJKZIQnjiloS7xBvDs1ReSZsLlsRZ41Z6rlPBOErtPYDzAxHp2IuhYksLPt5vwbqob8RKsaK4bJTXjdlbwPwnzvTcY4jBJsVDt3qRQMzxSUt3Hz5nKI=
  region: ap-northeast-1
  application: testapp
  deployment_group: testdeploy
  on:
    repo: yutaka-kimura/com-only
    branch: dev

branches:
  only: dev
  except: "/^(feacure|hotfix).*$/"
