language: php
script: ''
before_deploy: "echo 'Start Deploy.'"
deploy:
  provider: codedeploy
  access_key_id: AKIAIY5E5ZM7OHBWAQZA
  secret_access_key: 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
  region: ap-northeast-1
  application: testapp
  deployment_group: testdeploy
  on:
    repo: yutaka-kimura/com-only
    branch: dev
after_deploy: "echo 'End Deploy.'"

branches:
  only: dev
  except: "/^(feacure|hotfix).*$/"
