language: PHP
script: ''
deploy:
  matrix:
    - provider: codedeploy
      access_key_id: AKIAIY5E5ZM7OHBWAQZA
      secret_access_key:
        secure: iYnxmhtQNQUIMgtA8JLgrOQ8hdE3bN7hhp+56nD4mlVu3M9yKGxL63//safeWA3lOMOl3aIDPiUAcytRrZcrFUsSu9UeIPaBowrpJq/a8tEdp38SwogFVtkjZlBlzcNqU9sXNZ6jRIE4M1/XOEpS9rN6Vs9TGD3w9eza3siffWMpkGOXqln1Mp/6J5zL94DeZ+g6ShdtZxXYiKHG/Es/NPb3/4+biD7esGrtXKdQKRqQuY5v5H0vOY+3T/ZUUNBDX4/T0IXovFok2rxFj03wQfe0kCggo7acYi90WWeiELnbRIhdVlZrJ7PoOKxE+TQ/4Tnz7BjthUaK8BB51OZa5/GvlZqXVLZKyk0975uoX4zuTGnXDQhXMAc/EInohEQbD4qvGUJMcbLWFVNKlazOh8lTJgV9DjEn31nbdpQnZ5o6y4VxCTe0VcVmGZTIBLNfuXSzj87gZ2/Mw6kjsk5pdEiC66sETxc4UkozhqoFrukLelqwMCNECiWivpCfEJIq95zOpq28uXTX6+v9yp94WW9TXIUesXVsZvoadwqTOQz9hck3FjYAG2W4iLcxNeMz8koF1iaWLCx0W1AmNUv2qqcyU4V0jfP5E0u+4Hp4GW3QvtS3L3e9O0ozk3hErVp1oXlFlcgUUMnvrFGOrbztEHkDlwz+VCCO4RyDVbqjvRw=
      region: ap-northeast-1
      application: testapp
      deployment_group: testdeploy
      on:
        repo: yutaka-kimura/com-only
        branch: dev

ZZbranches:
  only: dev
  except: "/^(feature|hotfix).*$/"
