language: php
script: ''
before_deploy: echo 'Start Deploy.'
deploy:
  provider: codedeploy
  access_key_id: AKIAIY5E5ZM7OHBWAQZA
  region: ap-northeast-1
  application: testapp
  deployment_group: testdeploy
  on:
    repo: yutaka-kimura/com-only
    branch: dev
  secret_access_key:
    secure: iYuazVc3M8iuTvSnhybu+YO2zoLj2A6rJ0dSUk7rgN4PUPGz7mleaZWim09r/TZBtF/EaklBpSLCcCGi7fVTS3nxSd80Ly8UstYHpElEhExn3/0QOIVG6P/6zEqlqoAxOCQaIQEal0eNNYO/Ytb7MIBiyDAzyPSpNH6v0SFibCM3SanCcJIBa1kVC5RMEzCWHIEcjaX/32tMML7ojFHBeCh6iTujALw0rOZJBcjuGm0BjWZRqgKwKDhmG1r5wxzXFv+7b/jV2RZzdN+4ZPvkoTjEqXAOUL8sLmAXy9pQeEWdysGYo2O6Inciwy0LO89S9l7bJIMJwzeFehQ0RqGUHcPWcGKM/nEvJjXIXtJwhnONx9UuGDNn3f3Y538XVfXF2iHmv99lEHjJI9L6n5FXggjlBOf3J0aFaLG8Jrpw4IWzYz6qcRdFGVWWo4qvpO9g01u9vOFG6zdKRxW9h2y4FCQUzlFcw872znhnjSxWMPPLsXNSorZi3HTufMSE0tdibm0kMr8MoSyqmbZB+NgTmwHV3jDG2uiQ73GsaS2NO18TwQC1Y3wHK9RE38F4WiQTEN5i7PRmKXhGqs6EzlflzgEcLHEA5Ly3np/fT4qInWdBfRNzY57D1v6ypNhqDMJUBVHlryWTfSzK3rODhALjufZWREXnGmKOFEL9JmwZ6TU=
after_deploy: echo 'End Deploy.'
branches:
  only: dev
  except: "/^(feacure|hotfix).*$/"
