language: PHP
script: ''
deploy:
  - provider: codedeploy
    access_key_id:
        secure: nD8G7WcLxOEUjKobvpXuTId4Et9d+9KHfwuO1dWGinkhnow3zedvbevNMkfzhYDwaR7u5/eGBpKNYM+jCltVeUSUcuvQD1bPOnABDg98dJxEDMGzEctaiVUqckY6U/mc+ss1lK6SIYaG1EIBMdYjD/ljA908iCy3yX/JIl1DlPXKpx14autq87+fH8Vx0HYZK9ah9QZoWsDHzwqTs7FzKgiZZ5pJFmB79jqoPZhWeUk0Oe7MwzcLVJtjFlaM5TTSvUPFaGNceqNgZnzqVRNPQAIl03Umcm9HBuaaYvhamkUjhwRL5G1qfcPO6o/Kp1LyMADhJvyQOIR6G90hi1GuLFyoYiaq4LuJ9M2kGaP/SWXAgG74Ahh9SHsXTPRS+ApG81pQyRNV6BkcMA0v+6OJhC5Ujr4LLqXeg+NZ5n7990/cQzNr6SHgAhkM4awDpq1s986Wun49m8/fjbvpZkM5DxzBbTBU8jDgk+pnnjTukD59ZxkbUE9Q5Gri3h2hwHQ/yLnVw4jUZuwqQS/HYZwhDtZl4/T5ro31IhMUxDf5pEBv0mVRpMsJYC6smS8oyMI0pHMsKo8lBaR4JeFAUiY6WNONIntAabKtTfoDjtvyx8VnAWAVkTnPD7SQzR78oR8nEjw48E8VVe453/ikhBn+/LCg350gE0vHWat1fpFO60A=
    secret_access_key:
        secure: t1RS4n/C0rf05AQl2c6Of0myv47cgeOnZNQgPtgxJNYVZhkhImeXDRM2FIKsi4W5/TewWieCq/kkJt7KESH4Dqzk/9xUrI6cqibnrMhBQMUVBHnG3dXv1DsaILkdUOEsjp7RGlubxTBG7S+5E0qDjJbeEiOtdJL2shMH4SGMno/STAbsjJoEPVpBfkt+OD3NYSOUYWP5iTuLNGWWPlOXNiM/ZZjb/epNrx/qSo2LI51nr8BWDvwiNnz2uTx++WAUdY3+YFGoG7l5RvxgSRtqzmil3i575z7m54bWk3YY0CR/p61b+WBnN7LHWG8SB8D020dt7e9xc5j26Kvq/PecLecI7RpdaFy50DD9LF/AEHl3TMbQ2OYWmdExc/SR8WZ44QvZhvOMHw0FrLx79ysAVIORVqzmFLep4x1SSR6rPluJpUTySdpRB5N1OY3fqAI8+EIyGLxr5LXNdAqQBEUE+5NzjmnqtoXDc2urz/wyPz/ZJQdyRG/HyAyciEJN7wCKlCWN/bS4yVSTKCG7/IocI66wM9MiBuO1+ypMkHO0K78RKaxk3htqUGWIRbgDBLz6VATBJpErdOaC9jy37w9C2EtUif3UKUX1c4oDIBkZrbx5IuMW3JwviI7GwMkgLLaqs+rxn7xmTnulL3oc7tvrhfWurJi3QSJKk8wxBlvJzv4=
    region: ap-northeast-1
    application: testapp
    deployment_group: testdeploy
    on:
      repo: yutaka-kimura/com-only
      branch: dev

branches:
  only: dev
  except: /^(feature|hotfix).*$/
