language: php
script: ''
deploy:
  provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: ap-northeast-1
  application: testapp
  deployment_group: testdeploy
  on:
    repo: yutaka-kimura/com-only
    branch: dev
branches:
  only: dev
  except: "/^(feacure|hotfix).*$/"
env:
  global:
  - AWS_ACCESS_KEY=AKIAIY5E5ZM7OHBWAQZA
  - secure: pDkdikxoL177r5nxvLuHcI6pXW1npk/W3Cw3lgXwVX5HjchaYoc7nM7wxSM8bhLX4w2HZLuZIw9OrFDwwlScyUdF53NoXwTo/BjXwpB4/yb2F2kL4noivnlfPkk32tCG9/Pjo6U1IiZYgttQCiLMu4T0HadtfwKDLiFzzLJ0N8snJtLr4Lfvwbp8YmaE8tT/M8XSEZ8jOR+4XZdgcVGMY2fzI8PefG3ZrpFVk7RGXzWyPeMt9w2rYIUC9aH20jWyeKG80xXoUDKjZ3ZTfR5LxXgB7ZH/UIF7wBvxvxBEXNNV54Q6vwzo1UawwxSHqBxqHBtgsCT4CyQ9nostNWyNuY31Y/L3bGuK5xaIzvKSC+lcwiCV86PGtBaONuGtvtBbw/LcSsMvRt2T8CXpGXPsJc1ceDFNqYsuEWbuQgjgEo9Tveek/WYu11MczzuiBN8nMi6fIZbXJMPKfQSPvHD1U0JfIZDjUHwdNSsLsvvFSRlO8lARbNcyK8P7j3ki8OT2N5l5gKOm/yfEL0sEEDPah6seqyT20JtwuUvNdDTDOqL5lGmA4vtoP+cRG9Msj5y8Wxq+fFUPSlvJGMoToGbYcDf0h+GZz5SJDx9kd6efyaCdQBHRW4Y6GLA2PPeTlAnG/o3ycFa3j/X3MY6FnYtB8OeF2o+Aeu+v28hsZ0IqAK4=
