language: php
script: ''
deploy:
  provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: ap-northeast-1
  application: testapp
  deployment_group: testdeploy
  on:
    repo: yutaka-kimura/com-only
    branch: dev
branches:
  only: dev
  except: "/^(feacure|hotfix).*$/"

env:
  global:
    - AWS_ACCESS_KEY=AKIAIY5E5ZM7OHBWAQZA
    - secure: CsfKPMW4nvyuSPWgFYXmqfpdNUGJlccUTqU4PinKa7vaWst78PiQBLh53oJdn8bC7kUWCAcPhLFxkkLfdXypr1DJtH70Nshw+t4VGWQ3dQVvCkub3NlzmpQ8npHfnjpRpC8TOhCdfH9EiAA3KL2D/TbrGMyGKP6jAaatTgrheaej0BQ1dAIOKPhT2aaPlTVgY5w7n289U6p2I7nE/6sOqQR7+hM1pxEo3ItDS3zsmZdLEPGnKjCw5u9wMCCynb/64TaPvpE/+5dtTkqArjE9l1PNUJh+W+JLY61zaGHUyUcWm6DxwxePN5S34XkA/W0TW/GV3BU9zTlG5TOuN9X5hQnn9ZcXCPevuSF7TmcoFxyOXua17rv043Tn56ACo6+DJmmeAxtHNI0HyC1CeS86+3StVZ5YFJOqhtkku4jwpZx5E5bGt/D3QgwB1q9jztEXz5IvtDmxPADx5Hzktint+AXIO9kaNmH98Fhznhs603rgCk0F6BuUDasbTf1V52NX5x8xleUChc4LyOmG+NGI0IdwxBPq5iTZTcQdzxXHs5AS8RDA6N2LDY9IeIMkvva/2vTH4kHU/p6+Rm2heuGcJatAKwa5RjAcguoaY6drFhqXtDBWM6QdQqrZtsMAGEjVc2SZ0K5Ljhf9QL5XbOPMuIgLCGPuVrZ6BQbL5bWbZXM=
