language: php
scrupt: ''
deploy:
  provider: codedeploy
  access_key_id: AKIAIY5E5ZM7OHBWAQZA
  secret_access_key:
    secure: mxGbe4X5JhLqKHhfDOp4QgUYz/MvXRNET/e8jLPKkKUGD82TKUlgRyMOo/fM97lEo1PEuElwpl0LX+/ufiUlqRGomxl9Dbwst1MBsKaCrrxXU2baRmThujcSqc/OdhphfFvdMFF7a0NQ9RZyzPWu/wRd+chBn46Bd+eAx5NCjpLuqeCyue8A4mZTn+6MrPqxyzUDW4rve/KY/HgZDShSfV/kRi38nl4EQ6EJmefqCXQcUA4DuqWcwtz0EAPLiltFwfv12HB0oMLvDI5704AjMkCnY3SWEUMNEM7d7JJeV1TIRm1WIO+QtocnZX+Gy/YaYgDkz3X+6Nd0Y2To4g6WlF/A6rYMR4CDR1BTNqUKZ0JSiwVGZHAmJb3kvYeDSapC+DlTl/YgdwpQu7o3Ff50mWl8ShPpbROxH/4qO30UrOKILAIYQwSn8Bwd/xs7a/A4g2CK5VtuwFrilJbTbZI+9RYoo9pGqIwKDNeX+BRUMvmC9vcWoTWfrbm2cbXJr0wZzELCwIEVECCHMsT1NoB+YaLhRpxnBsEmb7W6hbCFu1/k1GYD+nDcbRm0qnYdn3UeNZQgkYyqLmYXLtZqE7493E5yUkds8GN0U5XCJuHwVvwDOnR3bpC/f79BytwuSUu0Zn39XCJVZWeKF0gFPhBMYef41a84chpCcaYZkxU1xFc=
  application: testapp
  deployment_group: testdeploy
  on:
    repo: yutaka-kimura/com-only
    branch: dev

branches:
  only: dev
  except: "/^(feacure|hotfix).*$/"
