language: PHP
script: ''
deploy:
  - provider: codedeploy
    access_key_id: AKIAIY5E5ZM7OHBWAQZA
    secret_access_key:
      secure: B4NV66Vu11fZv+s2t+SHly8gQ9w0+dTBoqHCDyqJ50uOYIrttGLqDAfM8zAFl8fHqaWOSSTi574icuHd6miATlp4ClzKAfH4YP3zpWk5wu1Ev5rUdV49wO5q0aHPDYk8qQd8uJ1FYdu7Kiyzl4WwxgW0uc58XnB2lMoZQJCGgyZYINiKBIZcqJVGF8apbwNZUfF9ucjo6FaFdo8p5wLabrjfRzlJE3D0qr3kUcobjtevSDS2ijPpKH5aDJpurPfOpqIWxdlzoL4CvyRAuaosAZ4trpC5TFJGVgKuavnn0KpV3WTODZMQlkC+BSoxDhEkeyuXgE2FTXMSXi1SnK7tulA2iI8fEAnWUoNDheAB2nm73TWfppSfwmQXOghDevXVPqim5gpZmq49tWNoXJVN4A7vK2sfOA9gb46Cvl60DGdqApgenUTvs+XT/hpT0plOyDVCkjlIiPoJmtJmPVgPs13yQyTiM1T3sXKu4Xd08/JyhAHJOS5kpa6SLhuXm7lGmcRrSRGCH/AigXO414cHdTzSqceNvvjkjP3aNR057YjzvXAIzZcapRp7GFVqvAYWLpYlB1DyLH4jrBAIM/vDx+1DuTOTCi4NTw3rmT7EttcEYsdGxLo3If4kznb9jaLNQ634c/QUryktCC2hm8yrTbXKwpeCsIFIStlYrn6X5E8=
    region: ap-northeast-1
    application: testapp
    deployment_group: testdeploy
    on:
      repo: yutaka-kimura/com-only
      branch: dev

branches:
  only: dev
  except: "/^(feature|hotfix).*$/"
