language: php
script: ''
deploy:
  - provider: codedeploy
    access_key_id: AKIAIY5E5ZM7OHBWAQZA
    secret_access_key:
      secure: eQIJOtCrZ4wUJehN9VlN6GDVF4IKHBaBrU/CmD79w9cH9Pvvg9fac2mcsI9oubAPqasBeTdPs2TzYPJQrxbUWeiXx+/euaB6IW+oU84TIAwv+WIUNTyMLn7H0TkRSw58mmiW7YtPmd5n1pyvatyWY4PPI0SK1iemb4YpgkZkyyQPusNp8im+NufH76lTvlK7aScieAipJVhndB2qmVZrVWnn52losspGxStESDAevNwYxrkZuUd/kriuPQn1PMyFkF7wVpffmTLUDNjIbCgVhdNwIINt7eiKrEQ+DGFTx8SId1wIN+HwXjfpX9HbW25vu/wE4AO2qo0smTeOmNNUdAJpAGfbREYf3vnBw925F5KNJfn7dtjp19DE+ga6U0Tw/sl2Io1qW+M+X0Ds+JflVKaXcxxa9IVrX5EI4ycNYt6yEGixIOuc9A6MD3+mRbd25B/zdon6U2RKPZIkm20ddOZSwyQj7ZypZDkAACcheavPhBAbAaQVW7aR8QlPrONSSygtqzDIAcTIfaSrkU8O0JqDRVK1MU0nPIr4Pr2Gap2G8vbpC2/BtIfYxENmeLHHw80mW1A7sYPcYzc+frPO3qGBbQLsZ0pPL5hV7kLw6rNyC5Twp2CUqgLRwTndga3iOwrDHm+jFbwGBquFvCrW7wZKSmNOfk2B0F84lg08ZVY=
    region: ap-northeast-1
    application: testapp
    deployment_group: testdeploy
    on:
      repo: yutaka-kimura/com-only
      branch: dev

branches:
  only: dev
  except: "/^(feature|hotfix).*$/"