language: php
script: ''
before_deploy: "echo 'Start Deploy.'"
deploy:
  provider: codedeploy
  access_key_id:
    secure: hk9v2bYni7w9D2EX4Np34SQ3n99X+SEfZwMDkaCuHCbHP4zno55HXwYmLAhg5sqCSIIUBCNNbWM4/opUfEhbXMYq+57dn38+PFyJDPWYSEHoPFepaUPqvb87wUI/YYuGwPplRnduVWcG7qcUvO41Hrav4flqyVB2RtQu4J3TUPvfyLoW4PIBv6cmq0OAtxz5tYbpVAtDPHG+GAr2i6OSvfIiDqNTj6F83jINukLq8VmHotF+elhJ2zzno84dfEGZhp/bN2qtWGNTe6eOv0DvxryEk6RwSLO7qegul6XOZnv8qh4LqYjigrq5utQzSsQdJfD9ijVScYbIUKRIL3X/IfmnYt3sqQrFnU8CbyUbMwXbNbPq0WT5/RMRJ5N/Xs/81ENo+Thui/GItSZuZ76mwEDr9DgZI6ZV9eJBWrBhe8ZMcTqaouAQGGtulZXob2QFpdaDkUYpEBoQt9KFYsJi/VLVg/H2b0NaLCSJm7/QvuujuGrTOkHnJPj4m0+LFHzFxITg1Q3QdjkftrmnOI8MAVr9mAD1DQXwupsLcLGYCp1qmaQx9ARIyl9ef/aG6OX2FGQc8XtAbXccq1uU3rQh/mspZItW3xMvASXyzUCeHmNiVSL5GwqSSjz0VQJvSxyO/fBnJUY3tKMDJPYcP8eKLUXV4Iug+ip8PBeTT1cUOO8=
  secret_access_key:
    secure: e1mAiTk3AqBJ2AVUZLVGEMT5DsVvhfO4XvCbOWyeQ611B7yb9QAtQ4rdmNiCzYdHTtAHxXGapHaGGE9h4KXGEcnUXknMgmHaoV3xrFYSEx1Ab8f+se50U6dt0YuEMe+c8EshLNlf7sDl2LK7IGMD7A7pV0X0kRl2iVWt0gYUf1K1lILKBZchvZXeeJPJbkTN0P16k7vzZ3DgbhfxbCR4Z/hTFUwDaB02a0OVDRMZSIewOumtugMxEp/dSyM1HrlES8evCV4q35g+gxbvPQsA5JKRmuaODaWkLK1Cjeg7l2SJFsfIhpWg1WrZ5UPjodo2mlx2PF3rzCRRKOdyhEdXOYIfekm5PK3dx4ZrMX69/pCP69OwAzTfrjJvdE6JDU7vTmEo3XMbf44q3W6iEdokIsRIi3WfrOjSh8CIgS5KctkIcqG7ebOpYXjU6zQG7+Pmu6nosVoyP2ZFhWRSWw43t/c5n23i37PJtTYve73Mm2+Sr72LeZDjqYk46QXjX65skC0dI9p6e+QVDVCGCd9xx3mm8SN/imnCCzdlU8MY4ynUOsIXLTsaL6ZAbxTjfykciL1S+dbiLGNLXUYgYkUYxaawzIA+dYhUYFjSy4cF1V5wvYxHH5wy68tdkMUYao+0sDdMBVLJngNq9uljZ7CD5lQ8dExz5xRE4rR7YJENqVg= 
  region: ap-northeast-1
  application: testapp
  deployment_group: testdeploy
  on:
    repo: yutaka-kimura/com-only
    branch: dev
after_deploy: "echo 'End Deploy.'"

branches:
  only: dev
  except: "/^(feacure|hotfix).*$/"
